### PR TITLE
Make code compilable with Qt 5.15 (some APIs gets deprecated). Close #73

### LINKED ISSUE #73: Build errors with Qt 5.15
I cloned quazip and build the zlib dependency.  
Than I run 
```
$ C:\Qt\5.15.0\mingw81_64\bin\qmake.exe "LIBS+=-L./zlib_windows/bin -lzlib1" "INCLUDEPATH += ./zlib_windows/include" PREFIX=../dist
$ make
```
and get the following output:
```
...
g++ -c -fno-keep-inline-dllexport -O2 -Wall -Wextra -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQUAZIP_BUILD -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DNOMINMAX -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I. -IC:/Qt/5.15.0/mingw81_64/include -IC:/Qt/5.15.0/mingw81_64/include/QtCore -Irelease -IC:/Qt/5.15.0/mingw81_64/mkspecs/win32-g++  -o release/moc_quazipfile.o release/moc_quazipfile.cpp
quazipfileinfo.cpp: In function ‘QFileDevice::Permissions permissionsFromExternalAttr(quint32)’:
quazipfileinfo.cpp:31:31: error: invalid conversion from ‘int’ to ‘QFileDevice::Permission’ [-fpermissive]
   31 |     QFile::Permissions perm = 0;
      |                               ^
      |                               |
      |                               int
In file included from C:/Qt/5.15.0/mingw81_64/include/QtCore/qglobal.h:1302,
                 from C:/Qt/5.15.0/mingw81_64/include/QtCore/qatomic.h:41,
                 from C:/Qt/5.15.0/mingw81_64/include/QtCore/qrefcount.h:43,
                 from C:/Qt/5.15.0/mingw81_64/include/QtCore/qbytearray.h:44,
                 from C:/Qt/5.15.0/mingw81_64/include/QtCore/QByteArray:1,
                 from quazipfileinfo.h:28,
                 from quazipfileinfo.cpp:25:
C:/Qt/5.15.0/mingw81_64/include/QtCore/qflags.h:121:41: note:   initializing argument 1 of ‘constexpr QFlags<T>::QFlags(Enum) [with Enum = QFileDevice::Permission]’
  121 |     Q_DECL_CONSTEXPR inline QFlags(Enum flags) noexcept : i(Int(flags)) {}
      |                                    ~~~~~^~~~~
quazipdir.cpp: In member function ‘bool QuaZipDir::cd(const QString&)’:
quazipdir.cpp:106:71: error: ‘SkipEmptyParts’ is not a member of ‘QString’
  106 |         QStringList path = dirName.split(QLatin1String("/"), QString::SkipEmptyParts);
      |                                                                       ^~~~~~~~~~~~~~
JlCompress.cpp: In static member function ‘static bool JlCompress::compressDir(QString, QString, bool)’:
JlCompress.cpp:264:56: error: invalid conversion from ‘int’ to ‘QDir::Filter’ [-fpermissive]
  264 |     return compressDir(fileCompressed, dir, recursive, 0);
      |                                                        ^
      |                                                        |
      |                                                        int
In file included from C:/Qt/5.15.0/mingw81_64/include/QtCore/qglobal.h:1302,
                 from C:/Qt/5.15.0/mingw81_64/include/QtCore/qchar.h:43,
                 from C:/Qt/5.15.0/mingw81_64/include/QtCore/qstring.h:49,
                 from C:/Qt/5.15.0/mingw81_64/include/QtCore/QString:1,
                 from quazip.h:28,
                 from JlCompress.h:29,
                 from JlCompress.cpp:26:
C:/Qt/5.15.0/mingw81_64/include/QtCore/qflags.h:121:41: note:   initializing argument 1 of ‘constexpr QFlags<T>::QFlags(Enum) [with Enum = QDir::Filter]’
  121 |     Q_DECL_CONSTEXPR inline QFlags(Enum flags) noexcept : i(Int(flags)) {}
      |                                    ~~~~~^~~~~
make[2]: *** [Makefile.Release:1045: release/quazipfileinfo.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile.Release:528: release/JlCompress.o] Error 1
make[2]: *** [Makefile.Release:900: release/quazipdir.o] Error 1
make[2]: Leaving directory '/c/Users/Leander Schulten/git_projects/Lichtsteuerung.git/src/lib/quazip/quazip/quazip'
make[1]: *** [Makefile:45: release] Error 2
make[1]: Leaving directory '/c/Users/Leander Schulten/git_projects/Lichtsteuerung.git/src/lib/quazip/quazip/quazip'
make: *** [Makefile:51: sub-quazip-make_first] Error 2
```

### PR DESCRIPTION
**Pull request by autoantwort**

### CODE REVIEW

File: quazip/quazipfileinfo.cpp [hunk 1]
```diff
@@ -28,7 +28,7 @@ see quazip/(un)zip.h files for details. Basically it's the zlib license.
 
 static QFile::Permissions permissionsFromExternalAttr(quint32 externalAttr) {
     quint32 uPerm = (externalAttr & 0xFFFF0000u) >> 16;
-    QFile::Permissions perm = 0;
+    QFile::Permissions perm;
```
Comment (RossRogers) [inline quazip/quazipfileinfo.cpp:31]: Is the value of enum `QFile::Permissions perm` initialized to zero? I would have thought that this line would only declare the variable, but not initialize it, thus keeping whatever value is on the stack, which may not be 0. Should it be `QFile::Permissions perm = {0}` ?  Maybe my understanding is for old versions of C++....

Comment (stachenov) [reply quazip/quazipfileinfo.cpp:31]: If this were a primitive type, or a structure without constructors (forgot the right terms), you would be right. But `QFile::Permissions` has a default constructor (it's actually a `QFlags`), and therefore it will be called here, thus initializing it to whatever the default constructor initializes it, in this case zero. It's true for all versions of C++.

Comment (RossRogers) [reply quazip/quazipfileinfo.cpp:31]: Thanks for clarifying.  I didn't look into macro `Q_DECLARE_FLAGS` as I should have.

Comment (stachenov) [reply quazip/quazipfileinfo.cpp:31]: The easiest way to figure it out wouldn't even involve looking into the macro. The docs for `QFileDevice::Permissions` say

> The `Permissions` type is a typedef for `QFlags<Permission>`. It stores an OR combination of `Permission` values.

Then you'd just have to follow the link to `QFlags`, and to its constructor:

> Constructs a `QFlags` object with no flags set.

It is documented pretty clearly what it does. Unlike many other cases where one really *have* to look into the sources to figure out how things really work (and then wonder if they are supposed to work like that or if it's just an implementation detail).
